### ISSUE TITLE
"ü" changed to "?"

### ISSUE THREAD

**Issue by elbsurfer** [bueltge/de_DE.php#12]
Any idea why "fünfzehn" is changed to "fu?nfzehn" ?

**Comment by Terrorpixel1991** [comment]
Same here.  ä = a? ö = o? ü = u? ....

**Comment by bueltge** [comment]
Is the topic always active on your installs? Which WP version is installed?

**Comment by jovelstefan** [comment]
Same here! WP version is 4.5.x (problem exists for some time now).

**Comment by Terrorpixel1991** [comment]
I have solved my problem as follows:
I have changed the database collation from utf8... to utf8mb4...

**Comment by bueltge** [comment]
This change was a step in a update release of WP. Is your WP a new fresh install or a older updated version?

**Comment by Terrorpixel1991** [comment]
It was an updated Version. I have installed it with duplicator on a new server with new database etc.

**Comment by jovelstefan** [comment]
changed db collation as proposed to utf8mb4, but without effect. :(

**Comment by bueltge** [comment]
In which file format is the plugin, Dropin in your install? Utf-8?

**Comment by jovelstefan** [comment]
encoding of the drop-in file is utf-8 indeed.

**Comment by jovelstefan** [comment]
i tried on another wp installation (different hoster) and encounter the same problem

**Comment by bueltge** [comment]
@jovelstefan but also a single installation and active as drop-in or plugin? 
I will check this and maybe now more work on a new release, include the other changes from other issues.

**Comment by jovelstefan** [comment]
@bueltge active as drop-in. I can try to add as plugin if you like but I guess that's not expected to make any difference? What do you mean by single installation? I have some plugins running. o42-clean-umlauts as well but deactivating this does not change anything either...

**Comment by bueltge** [comment]
Normally, the difference between plugin or dropin should not have an effect, but all is possible.
Single installation, Default WP, again to the [Multisite](https://codex.wordpress.org/Create_A_Network) installation.
Can you also test, deactivate all plugins, use a default core theme. This was also really helpful to select the problem, that is really in the dropin/plugin de_DE.
Thanks!

**Comment by bueltge** [comment]
@jovelstefan I have tested it, now. Several tests, in posts, pages, category, tags, custom post type - always works fine. The core set strings like üöäÜÖÄ, not more. The plugin doing this also with ß and €, maybe you check this. Important is, that you not have a other plugin active for testing.

**Comment by jovelstefan** [comment]
@bueltge I just ran another test on a third installation, same behaviour.
- WP 4.6 (just updated)
- single installation with dropin in language folder
- no other plugin active
- standard theme Classic activated
- tested with jpg-file using different combinations of umlauts as file name
- example result: ä-Ö-ü-ß-€.jpg converts to a?-o?-u?-ss-e.jpg
If you are interested to chase this further I might think of giving you access to the site (but it's hosted on a shared server at a service provider)?

**Comment by bueltge** [comment]
Can you test this on the permalinks, create a post, status draft, with Umlaut in the title.

**Comment by jovelstefan** [comment]
for permalinks it works fine: http://autocompleted.jovelstefan.de/test-aeoeue/

**Comment by elbsurfer** [comment]
Permalinks are automatically cleaned by WordPress. I do not understand why WP has this functionality built in for Permalinks but is not using it for images...

**Comment by bueltge** [comment]
But WP core have only `üöäÜÖÄß`, not more, like the `€` sign. I check the upload again, in two other different installs, also works fine. My test file `üöäÜÖÄß€.jpg` changed to `ueoeaeueoeaesse.jpg`. All tables in the DB are in `utf8mb4_unicode_ci` Collation. The Db self is `utf8_general_ci` as example, also an updated WP.

**Comment by jovelstefan** [comment]
@bueltge any other idea what to do now?

**Comment by bueltge** [comment]
Not really. How is your database settings? Do you have really no plugins or functions in themes active, that have the chance to change this filter hook?

**Comment by bueltge** [comment]
Maybe, I have an idea. How is your upload process, maybe the ajax process is different and we must enhance the dropin with the ajax hook to filter the name?

**Comment by jovelstefan** [comment]
just used the "browser uploader". also the same behaviour :(
there is definitely no active plugin and the "Default" theme is activated.
database collation and all tables are utf8mb4_unicode_ci.

another idea: can i somehow manipulate the dropin to change the umlaut replacement somehow to gather more information? at least € and ß are replaced as expected.

**Comment by bueltge** [comment]
Yes, you should only change the `$umlaut_chars['perma']`, maybe in Line 67, `$umlaut_chars['perma'] = array( 'Test-Ae', 'Test-ae', 'Test-Oe', 'Test-oe', 'Test-Ue', 'Test-ue', 'Test-ss', 'Test-EUR' );`
You can play with that for the result.

**Comment by jovelstefan** [comment]
now it's getting even stranger, result: "a?a?o?o?u?u?test-sse.jpg" -> So the umlauts were replaced with question marks, the ß was replaced as expected ("test-ss") and the € was replaced by an "e". I don't get it. What I'll do next: Setup a completely new, clean WP and try again. I'll keep you posted, @bueltge ...

**Comment by bueltge** [comment]
Thanks, strange and we should find this problem.

**Comment by greatestview** [comment]
Same here, `Hässliches Entlein.jpg` becomes `ha?ssliches-entlein.jpg`. Stangely the Dropin is working perfectly on our lokal machine, but not on our live system. Must be some different configurations? But ideally this Dropin should not depend on server configurations. Hmm.

**Comment by bueltge** [comment]
The dropin/plugin use only php, wordpress functions, I can't see a depends to the server configuration. Also no problems on tests locally, online on different servers. If you could help me, I'm really thankful for feedback or the right hint.

**Comment by bueltge** [comment]
Maybe new feedback, tests?

**Comment by Big2k** [comment]
Hi Frank,
same issue here on a Profihost Server. Installed with the Browserupload. 

Umlaute inside post title are fine. ÄÖÜß€ = aeoeuesseur

> ### MySQL ###
> Version: 5.6.35-1
> ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
> 
> ### WordPress Environment ###
> WP Version: 4.7.3
> WP Multisite: –
> WP Memory Limit: 256 MB
> WP Debug Mode: –
> Language: de_DE
> 
> ### Server Environment ###
> Server Info: Apache
> PHP Version: 7.0.15
> PHP Post Max Size: 50 MB
> PHP Time Limit: 300
> PHP Max Input Vars: 1620
> SUHOSIN Installed: –
> ZipArchive: ✔
> MySQL Version: 5.6.35
> Max Upload Size: 50 MB
> DOMDocument: ✔
> WP Remote Get: ✔
> WP Remote Post: ✔
> GD Library: bundled (2.1.0 compatible)
> 
> ### Active Plugins (15) ###
> Advanced Custom Fields: von Elliot Condon
> Autoptimize: von Frank Goossens (futtta)
> Broken Link Checker: von Janis Elsts, Vladimir Prelovac
> Contact Form 7: von Takayuki Miyoshi
> Credit Tracker: von Labs64
> de_DE: von Frank Bültge, Heiko Rabe
> Download Monitor: von Never5
> Duplicate Post: von Enrico Battocchi
> Fusion Builder: von ThemeFusion
> Fusion Core: von ThemeFusion
> Redirector: von Ralf Hortt
> Slider Revolution: von ThemePunch
> Yoast SEO: von Team Yoast
> WP-Mail-SMTP: von Callum Macdonald
> WP Media folder: von Joomunited

**Comment by bueltge** [comment]
How do you upload the file? I checked again via "Medien" and also in the Media Modal on posts, pages. Always change the dropin the filename correctly. Have you active the solution as plugin or dropin?

**Comment by Big2k** [comment]
First i've disabled WP Media Folder. And deleted die Plugin.

I tried every option.
1.  Dropin - Upload to content/languages because we use define another WP_CONTENT_DIR.
2. Plugin - FTP Upload to content/plugins.
3. Plugin - Browser Upload

I am using the Version from this Git.

**Comment by bueltge** [comment]
And always on a upload you have the problem with Umlauts? crazy.

**Comment by Big2k** [comment]
Yes. Used your new commit and stil the same.

> de_DE.php/de_DE.php: text/x-php; charset=utf-8

**Comment by bueltge** [comment]
Maybe other one can help, debug this problem on a server, there have this problem? The names of the functions should be speaking about his goal, but he has also a small documentation.

**Comment by user121216** [comment]
I had the same problem and got a solution.

Is that right, that everyone with the problem is using macOS? The filename representation on macOS are different to Linux or Windows. Here is one explaination (http://apple.stackexchange.com/a/10484).

My solution is to normalize the filename:
```
de_DE.php
 	function de_DE_umlaut_filename( $filename ) {
 		global $umlaut_chars;
 
+		$filename = Normalizer::normalize($filename);
 		if ( seems_utf8( $filename ) ) {
 			$invalid_latin_chars = array(
 				chr( 197 ) . chr( 146 )              => 'OE',
```
You only have to check if php extension common is installed. I had to install it, e.g.
```
apt-get install php5.6-common
```
I hope it can help you.

**Comment by bueltge** [comment]
@user121216 I have add this idea to test it again. Thanks a lot. 

@Big2k Please can you also test this new version, maybe this is the simple solution to this problem. Thanks again.

**Comment by Big2k** [comment]
@bueltge on my setup it's stil broken. I am using the de_DE.php 0.7.11 (Commit 939782aa96c5c37c68d2a55b942d43d1b69fbdd4) as Plugin.

![screenshot 2017-03-30 10 14 26](https://cloud.githubusercontent.com/assets/20796742/24494210/c8ba3e0a-1531-11e7-867b-0950097869be.png)

**Comment by user121216** [comment]
Did you reupload the files? ;)

**Comment by Big2k** [comment]
Yes, sure. 😂 
Deactivated the plugin, deleted it, downloaded newest commit, uploaded via FTP the de_DE.php,activated it, created the test files and took the Screenshot.

**Comment by bueltge** [comment]
But maybe the class is not existent. That is only possible to check via debug access, ftp, admin.

**Comment by Big2k** [comment]
I'll send you the logins via mail in the afternoon.

**Comment by cfoellmann** [comment]
can we use http://poopy.life/ to test this?

**Comment by bueltge** [comment]
@cfoellmann Maybe. It is really new and I don't know about this background.

**Comment by user121216** [comment]
I checked your commit.  There is a mistake:
```
if ( ! class_exists( 'Normalizer' ) ) {
```
The class should exists as condition... ;)

**Comment by Big2k** [comment]
Last commit looks nice @bueltge It works for me and look right.
![screenshot 2017-04-01 07 25 31](https://cloud.githubusercontent.com/assets/20796742/24575669/26be4f4c-16ad-11e7-9754-56b221768935.png)

**Comment by bueltge** [comment]
Really great, thanks also again for your feedback, time and access to your install.

**Comment by bueltge** [comment]
Thanks again to @user121216

**Comment by bueltge** [comment]
The current version is tagged with 0.7.11 - https://github.com/bueltge/de_DE.php/releases/tag/0.7.11

**Comment by greatestview** [comment]
Works (Plugin version)! Thank you!

**Comment by jovelstefan** [comment]
Thanks to all of you. DAU question: My WP runs on a standard hosting package and common/intl are not part of the setup. That means the update is not working for me at all, correct? I will change/upgrade my provider then... ;)

**Comment by bueltge** [comment]
Hi @jovelstefan No, not at first. Maybe I can get access for admin/ftp to debug this?

**Comment by jovelstefan** [comment]
@bueltge I sent an email with access data...

**Comment by bueltge** [comment]
@jovelstefan thanks again for the access and chance to see in this host. I was possible to debug this and add an alternate simple solution for missing Nomalizer class. Please test deply in your install. The last version is active as dropin.

@Big2k @greatestview Please can you also test again with the new version 0.7.12?

Thanks a lot for all your help.

**Comment by jovelstefan** [comment]
No success unfortunately. :(
äöüß€ÄÖÜ.jpg becomes a?o?u?sseura?o?u?.jpg
(running into else-statement as expected)

**Comment by Big2k** [comment]
Test with version 0.7.12 on Mac OS X and Chrome.

[äöüßÄÖÜß.txt](https://github.com/bueltge/de_DE.php/files/902564/aoussAOUss.txt)
![screenshot 2017-04-06 14 58 03](https://cloud.githubusercontent.com/assets/20796742/24755179/7e1d19fa-1ad9-11e7-9034-3e7c19b4355b.png)

**Comment by bueltge** [comment]
Thanks a lot @Big2k 
Please use the last version, commit before 2 seconds and test again. :heart:

**Comment by Big2k** [comment]
Test with commit #60a69d8
![screenshot 2017-04-06 15 07 11](https://cloud.githubusercontent.com/assets/20796742/24755514/dfbad11a-1ada-11e7-87d6-dfb1b7e6dd38.png)

**Comment by jovelstefan** [comment]
Test with commit #60a69d8 on Mac OS X and Chrome as Dropin.
No change at all :(

**Comment by bueltge** [comment]
So, many playing with the different files. I add a simple but hard replacement for non default strings to upload a file with real utf-8 strings. 
Please test again and give me feedback with version 0.7.14. Thanks a lot. Small hint, if the `Normalizer` class is existent it should have no changes.

**Comment by jovelstefan** [comment]
confirmed positive! :)

**Comment by bueltge** [comment]
The plugin is now also available via wordpress.org  https://wordpress.org/plugins/de_de/ 
So it is possible to get automatically an update, if is active as plugin.

**Comment by Big2k** [comment]
Installed 7.1.4 and everything seems to be fine. :-) Nice job @bueltge <3

**Comment by bueltge** [comment]
Vielen Dank @jovelstefan @Big2k 
Der Download auf https://wordpress.org/plugins/de_de/ funktioniert nun auch, wer es also als Plugin aktiv hat, sollte Updates ab nun automatisch bekommen.

**Comment by greatestview** [comment]
Thank you! Was just about to ask, if you could submit de_DE to WordPress.org. 🙂
