### ISSUE TITLE
Links in readme.md are not working

### ISSUE THREAD

**Issue by Zodiac1978** [bueltge/de_DE.php#15]
Site upgrade in progress
http://www.code-styling.de/deutsch/permalinks-mit-umlauten-ohne-o42-clean-umlauts

Diese Verbindung ist nicht sicher
http://wordpress-buch.bueltge.de/das-wordpress-buch/downloads/extra/

**Comment by bueltge** [comment]
Fixed with #14 Thanks a lot @Zodiac1978 :heart:

**Comment by bueltge** [comment]
Link zwei ist richtig, noch - ziehe gerade meinen kompletten Server um, daher diese Vorkommnisse.
